import Image from 'next/image';
import './globals.css';
import { Be_Vietnam_Pro } from 'next/font/google';
import hamburger from './assets/svg/icon-hamburger.svg';
import LogoIcon from './assets/svg/LogoIcon';

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${beVietnamPro.className} text-sm text-dark-grayish-blue`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}

function Header() {
  return (
    <header className='flex items-center justify-between px-5 py-10'>
      <LogoIcon type='primary' />
      <Image src={hamburger} height={21} width={30} alt='hamburger' />
    </header>
  );
}
